### ISSUE TITLE
Existing `Save-Data` vs. to-be-defined new `Sec-CH-Prefers-Reduced-Data`

### ISSUE THREAD

**Issue by tomayac** [WICG/user-preference-media-features-headers#2]
[Save-Data](https://wicg.github.io/savedata/#save-data-request-header-field) already defines a `Save-Data` client hint header. Should the present spec then define `Sec-CH-Prefers-Reduced-Data` for consistency as an alias of `Save-Data`?

**Comment by Kilian** [comment]
Given that `Save-Data` is already used in the wild and is also part of the (beta) `navigator.connection` API I would be in favor of aliasing them.

**Comment by tomayac** [comment]
Closed via https://github.com/WICG/user-preference-media-features-headers/commit/4a037009a6189d5cc0fcb7d1ed1e24013d373397.
