### ISSUE TITLE
Possible error in the spec in the section: 3.2. Policy-controlled features

### ISSUE THREAD

**Issue by summercms** [WICG/user-preference-media-features-headers#5]
The spec section found here: https://wicg.github.io/user-preference-media-features-headers/#policy-controlled-features

It lists the permissions policy as:

```
ch-sec-prefers-reduced-motion which has a [default allowlist](https://w3c.github.io/webappsec-permissions-policy/#default-allowlist) of `self`

ch-sec-prefers-reduced-transparency which has a [default allowlist](https://w3c.github.io/webappsec-permissions-policy/#default-allowlist) of `self`

ch-sec-prefers-contrast which has a [default allowlist](https://w3c.github.io/webappsec-permissions-policy/#default-allowlist) of `self`

ch-sec-prefers-forced-colors which has a [default allowlist](https://w3c.github.io/webappsec-permissions-policy/#default-allowlist) of `self`

ch-sec-prefers-color-scheme which has a [default allowlist](https://w3c.github.io/webappsec-permissions-policy/#default-allowlist) of `self`
```

However after speaking to some of the Google Chrome team, they told me that they do not add the `sec-` part for example:

### Incorrect

```
ch-sec-prefers-color-scheme
```

### Correct

```
ch-prefers-color-scheme
```

Please see the code line in Google Chromium: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/permissions_policy/permissions_policy_features.json5;l=116-119?q=bluetooth%20permissions-policy&start=11

It says:

```
{
    name: "ClientHintPrefersColorScheme",
    permissions_policy_name: "ch-prefers-color-scheme",
},
```

Therefore I'm opening an issue to double check if the spec needs changing to remove the `sec-` part in section 3.2.

Thanks.

cc Authors: @tomayac @beaufortfrancois

**Comment by tomayac** [comment]
It seems this is reversed somehow. Should it be `sec-ch-*` instead of `ch-sec-*`? Maybe then the `sec-` can be removed in the source code, because it just means secure context and is implicitly implied. @beaufortfrancois, what’s your thoughts on this?

**Comment by beaufortfrancois** [comment]
I've just uploaded https://github.com/WICG/user-preference-media-features-headers/pull/6
